extends: airbnb-base
installedESLint: true
plugins:
  - import
env:
  browser: true
  node: true
globals:
  describe: true
  it: true
  expect: true
  beforeEach: true
rules:
  import/no-extraneous-dependencies: off
