environment:
  matrix:
  # node.js
  - nodejs_version: "6.9"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g bower
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
